(deftheme bismuth
  "A theme that I have created while on the bed.")

(custom-theme-set-faces
 'bismuth
 '(isearch ((t (:inherit highlight))))
 '(link ((t (:foreground "#a5cae4" :underline t))))
 '(link-visited ((t (:foreground "#c57dce" :inherit link))))
 '(mode-line ((t (:background "#2b2e35" :foreground "#e1e1e1" :box nil))))
 '(highlight ((t (:background "#2b2e35"))))
 '(custom-button ((t (:background "#2b2e35" :foreground "#e1e1e1" :box (:line-width (1 . 1) :color "#000000" :style flat-button) :width semi-expanded))))
 '(minibuffer-prompt ((t (:foreground "#a5cae4"))))
 '(custom-button-pressed ((t (:background "#000000" :foreground "#e1e1e1" :box (:line-width (1 . 1) :color "#2b2e35" :style flat-button)))))
 '(region ((t (:extend t :background "#414348"))))
 '(font-lock-keyword-face ((t (:foreground "#c57dce" :weight bold))))
 '(font-lock-function-name-face ((t (:foreground "#425dcf" :weight bold))))
 '(font-lock-number-face ((t (:foreground "#f58e29" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#c32e2e" :weight bold))))
 '(font-lock-constant-face ((t (:foreground "#c57dce" :weight bold))))
 '(font-lock-type-face ((t (:foreground "#c58181" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#88f16c" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#606a83" :slant italic))))
 '(custom-button-mouse ((t (:background "#2b2e35" :foreground "#a5cae4" :box (:line-width (1 . 1) :color "#a5cae4" :style flat-button)))))
 '(shadow ((t (:foreground "#606a83"))))
 '(fringe ((t (:background "#1b1e23" :foreground "#e1e1e1"))))
 '(line-number ((t (:foreground "#454a53" :inherit default))))
 '(mode-line-buffer-id ((t (:foreground "#a5cae4" :weight bold))))
 '(ivy-current-match ((t (:extend t :background "#a5cae4" :foreground "#1b1e23"))))
 '(ivy-minibuffer-match-face-1 ((t (:background "#727fd0" :weight bold))))
 '(ivy-minibuffer-match-face-2 ((t (:background "#425dcf" :weight bold))))
 '(ivy-minibuffer-match-face-3 ((t (:background "#c57dce" :weight bold))))
 '(ivy-minibuffer-match-face-4 ((t (:background "#734aae" :weight bold))))
 '(org-block ((t (:extend t :background "#101619"))))
 '(dired-directory ((t (:foreground "#727fd0" :weight bold))))
 '(ansi-color-black ((t (:background "#1b1e23" :foreground "#1b1e23"))))
 '(ansi-color-red ((t (:background "#c32e2e" :foreground "#c32e2e"))))
 '(ansi-color-green ((t (:background "#3ec41a" :foreground "#3ec41a"))))
 '(ansi-color-yellow ((t (:background "#f58e29" :foreground "#f58e29"))))
 '(ansi-color-blue ((t (:background "#425dcf" :foreground "#425dcf"))))
 '(ansi-color-magenta ((t (:background "#734aae" :foreground "#734aae"))))
 '(ansi-color-cyan ((t (:background "#5cccda" :foreground "#5cccda"))))
 '(ansi-color-white ((t (:background "#e1e1e1" :foreground "#e1e1e1"))))
 '(ansi-color-bright-black ((t (:background "#414348" :foreground "#414348"))))
 '(ansi-color-bright-red ((t (:background "#c58181" :foreground "#c58181"))))
 '(ansi-color-bright-green ((t (:background "#88f16c" :foreground "#88f16c"))))
 '(ansi-color-bright-yellow ((t (:background "#f1e35e" :foreground "#f1e35e"))))
 '(ansi-color-bright-blue ((t (:background "#727fd0" :foreground "#727fd0"))))
 '(ansi-color-bright-magenta ((t (:background "#c57dce" :foreground "#c57dce"))))
 '(ansi-color-bright-cyan ((t (:background "#a5cae4" :foreground "#a5cae4"))))
 '(ansi-color-bright-white ((t (:background "#f2f2f2" :foreground "#f2f2f2"))))
 '(tab-bar ((t (:foreground "#e1e1e1" :background "#2b2e35" :inherit variable-pitch))))
 '(mode-line-inactive ((t (:weight light :box nil :foreground "#606a83" :background "#414348" :inherit mode-line))))
 '(tab-bar-tab ((t (:background "#1b1e23" :foreground "#e1e1e1"))))
 '(tab-bar-tab-inactive ((t (:background "#414348" :inherit tab-bar-tab))))
 '(rainbow-delimiters-base-error-face ((t (:inherit rainbow-delimiters-base-face :foreground "#c32e2e" :weight bold))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit rainbow-delimiters-base-face :foreground "#c58181" :weight bold))))
 '(rainbow-delimiters-depth-2-face ((t (:weight bold :foreground "#ffa956" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit rainbow-delimiters-base-face :foreground "#f1e35e" :weight bold))))
 '(rainbow-delimiters-depth-4-face ((t (:weight bold :foreground "#3ec41a" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit rainbow-delimiters-base-face :foreground "#88f16c" :weight bold))))
 '(rainbow-delimiters-depth-6-face ((t (:weight bold :foreground "#a5cae4" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit rainbow-delimiters-base-face :foreground "#727fd0" :weight bold))))
 '(rainbow-delimiters-depth-8-face ((t (:weight bold :foreground "#425dcf" :inherit rainbow-delimiters-base-face))))
 '(rainbow-delimiters-depth-9-face ((t (:weight bold :foreground "#c57dce" :inherit rainbow-delimiters-base-face))))
 '(mode-line-highlight ((t (:inverse-video t))))
 '(window-divider ((t (:foreground "#2b2e35"))))
 '(window-divider-first-pixel ((t (:foreground "#606a83"))))
 '(window-divider-last-pixel ((t (:foreground "#414348"))))
 '(vertical-border ((t (:foreground "#2b2e35"))))
 '(company-tooltip ((t (:background "#414348"))))
 '(company-tooltip-selection ((t (:background "#606a83"))))
 '(default ((t (:background "#1b1e23" :foreground "#e1e1e1" :foundry "ADBO" :family "FiraCode")))))

(provide-theme 'bismuth)
